# Generated by Django 3.1.3 on 2020-12-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name_of_sale',
            new_name='name',
        ),
    ]
