# Generated by Django 3.1.3 on 2020-12-26 19:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201226_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='projector',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='mymodel',
            unique_together={('room_id', 'date')},
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field2',
        ),
    ]
